### ISSUE TITLE
`update-docs` command requires i/o to be matching filetypes

### ISSUE THREAD

**Issue by jwlawrence** [rwjblue/codemod-cli#120]
I'm looking to write transforms that convert one file type to another (eg. js > json) but the `update-docs` command expects the input/output filetypes to be the same.

I'm happy to take a stab at making this more flexible if someone has an approach in mind already and there isn't an issue with having different file extensions.

**Comment by jwlawrence** [comment]
Opened https://github.com/rwjblue/codemod-cli/pull/121

**Comment by rwjblue** [comment]
Fixed by #121
