### ISSUE TITLE
Compatibility with ember-template-recast v5

### ISSUE THREAD

**Issue by simonihmig** [rwjblue/codemod-cli#155]
We need to update ember-template-recast to v5, which seems to have some breaking changes. See https://github.com/rwjblue/codemod-cli/pull/138

Making things worse, when running a codemod with `npx` within a project that already has v5 in its `node_modules`, node will take this version instead, which breaks the codemod with `Cannot destructure property 'parse' of 'undefined' as it is undefined.`. (Same as the dependabot PR's CI failure: https://github.com/rwjblue/codemod-cli/pull/138/checks?check_run_id=1807589103#step:5:138)

**Comment by rwjblue** [comment]
> Making things worse, when running a codemod with npx within a project that already has v5 in its node_modules, node will take this version instead, which breaks the codemod with Cannot destructure property 'parse' of 'undefined' as it is undefined.

We can fix the error by changing this:

https://github.com/rwjblue/codemod-cli/blob/461e100bf46ced706b010878fe13465cc47d45ef/src/bin-support.js#L60-L66

To:

```
 let templateRecastBinPath = path.join(
   path.dirname(require.resolve('ember-template-recast/package'),
   'lib',
   'bin.js'
 );
 return execa(templateRecastBinPath, ', binOptions, { 
   stdio: 'inherit', 
   preferLocal: true, 
   env: { 
     CODEMOD_CLI_ARGS: JSON.stringify(options), 
   }, 
 }); 
```

**Comment by rajasegar-c** [comment]
@rwjblue  Did we cut a release with the PR changes , I am still getting the error mentioned in #267
Also the ember-template-recast version is still 4.x

**Comment by rwjblue** [comment]
Actually, I just figured out what you ran into here. Checkout my comment in [`e57cd1a` (#201)](https://github.com/rwjblue/codemod-cli/pull/201/commits/e57cd1a9d709c83d9788e9dfc252beb67a054b79) for details.
