### ISSUE TITLE
Account for decorators and other experimental syntaxes

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/codemod-cli#38]
See https://github.com/facebook/jscodeshift/issues/256 for context.

**Comment by rwjblue** [comment]
We should add some tests to be certain.

@allthesignals - Would one of you happen to have time to try adding a test that included decorator syntax to confirm?  I'm thinking we can make another test like this one (but using decorator syntax):

https://github.com/rwjblue/codemod-cli/blob/7095e7574c033c769104937e64be8865fd166a4e/tests/cli-test.js#L294-L315

**Comment by allthesignals** [comment]
@rwjblue sure I'll take a look - thanks!

**Comment by allthesignals** [comment]
Hi @rwjblue, I added some tests here: https://github.com/rwjblue/codemod-cli/pull/39.

They don't seem to be catching anything (they pass) - open to guidance, sorry if this is wrong!

**Comment by rwjblue** [comment]
Thanks to @allthesignals in https://github.com/rwjblue/codemod-cli/pull/39, we have confirmed that all is working fine here. 🎉
