### ISSUE TITLE
[Q] Read "__testfixtures__/" recursively

### ISSUE THREAD

**Issue by ro0gr** [rwjblue/codemod-cli#43]
Currently all the fixtures in the `__testfixtures__/` sub-direcrtories are [ignored](https://github.com/rwjblue/codemod-cli/blob/b264eafa693989be3299f41b359630baf2b202da/src/test-support.js#L26) by test helpers, so you have to keep all your fixtures flattened.

I think it's better to allow nested directories by switching to something like `walkSync`. Makes sense?

**Comment by rwjblue** [comment]
Yep. Definitely agree.

**Comment by ro0gr** [comment]
closed by https://github.com/rwjblue/codemod-cli/pull/46
