### ISSUE TITLE
Document debugging

### ISSUE THREAD

**Issue by lukemelia** [rwjblue/codemod-cli#49]
Currently trying to figure out how to get a breakpoint in a codemod and wishing it were documented. 😄

**Comment by rwjblue** [comment]
I think the easiest thing to do would be to use `ndb`, which ensures any sub processes that are launched are also connected to the outer debugging session. It’s somewhat of a game changer...

**Comment by rajasegar** [comment]
@lukemelia @rwjblue Will this help
https://github.com/rajasegar/ember-angle-brackets-codemod#debugging-workflow
If yes, I can raise a PR  to update the README

**Comment by rwjblue** [comment]
Yes, that looks like a great start! FWIW, I think you need to use `--runInBand` flag for the `debugger` statements to be hit when focusing the test with `jest` (I usually use something like `node --inspect-brk ./node_modules/.bin/jest --testNamePattern "ember-concurrency transforms correctly" --runInBand`).
